#!/bin/bash
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
      - kafka-net
  server:
    build: './src/exchange'
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - kafka
    networks:
      - kafka-net
  api:
    build: ./src/api
    ports:
      - 8082:8082
    restart: on-failure
    depends_on:
      - server
      - kafka
    networks:
      - kafka-net
  pricefeeder:
    build: ./src/pricefeeder
    restart: on-failure
    depends_on:
      - server
      - api
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge